name: credentials-publish-dev

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    steps:
      - name: publish-credentials
        run: |
          jq -n \
            --arg account_id "$CLOUDFLARE_ACCOUNT_ID" \
            --arg access_key_id "$CLIENT_R2_RO_DEV_ACCESS_KEY_ID" \
            --arg secret_access_key "$CLIENT_R2_RO_DEV_SECRET_ACCESS_KEY" \
            '{R2_ACCOUNT_ID: $account_id, R2_ACCESS_KEY_ID: $access_key_id, R2_SECRET_ACCESS_KEY: $secret_access_key}' \
            > credentials.json
          aws s3 cp credentials.json "s3://${R2_BUCKET_NAME}/credentials.json" \
            --content-type application/json \
            --cache-control "max-age=60"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ vars.DATASETS_BUCKET_DEV }}
          CLIENT_R2_RO_DEV_ACCESS_KEY_ID: ${{ secrets.CLIENT_R2_RO_DEV_ACCESS_KEY_ID }}
          CLIENT_R2_RO_DEV_SECRET_ACCESS_KEY: ${{ secrets.CLIENT_R2_RO_DEV_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLIENT_R2_RW_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLIENT_R2_RW_DEV_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ vars.R2_ENDPOINT_URL }}
          AWS_DEFAULT_REGION: auto
