name: python-test

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: python-test-${{ matrix.config.os }}-${{ matrix.config.python }}
    runs-on: ${{ matrix.config.os }}
    env:
      BB_ENV: dev
    defaults:
      run:
        working-directory: python
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   python: "3.14"}
          - {os: windows-latest, python: "3.14"}
          - {os: ubuntu-latest,  python: "3.14"}
          - {os: ubuntu-latest,  python: "3.13"}
          - {os: ubuntu-latest,  python: "3.12"}
          - {os: ubuntu-latest,  python: "3.11"}
    steps:
      - name: check-out-repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: install-uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ matrix.config.python }}
          working-directory: python
          enable-cache: true
      - name: run-tests
        run: uv run pytest tests/