name: python-publish-dev

on:
  push:
    branches: ["main"]

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: python
    steps:
      - name: check-out-repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: install-uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          working-directory: python
      - name: bump-dev-version
        run: uv version "$(uv version --short).dev$(git rev-list --count HEAD)"
      - name: build-package
        run: uv build
      - name: publish-package
        run: uv publish --publish-url https://test.pypi.org/legacy/
